# Generated by Django 3.2 on 2021-04-30 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('total_faculty', models.IntegerField()),
            ],
            options={
                'db_table': 'Department',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fac_name', models.CharField(max_length=50)),
                ('fac_user_name', models.CharField(max_length=50)),
                ('fac_password', models.CharField(max_length=25)),
                ('fac_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_br_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sub_name', models.CharField(max_length=50)),
                ('sem_no', models.IntegerField()),
                ('sub_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_user_name', models.CharField(max_length=50)),
                ('stu_password', models.CharField(max_length=25)),
                ('stu_feebalance', models.IntegerField()),
                ('stu_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Teaches',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.faculty')),
                ('sub_br_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
            options={
                'db_table': 'Teaches',
                'unique_together': {('f_id', 'sub_br_id')},
            },
        ),
        migrations.CreateModel(
            name='SemAttendance',
            fields=[
                ('att_id', models.AutoField(primary_key=True, serialize=False)),
                ('sem', models.IntegerField()),
                ('sub_tot_attendance', models.IntegerField(default=0)),
                ('sub_tot_present', models.IntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.department')),
                ('stud_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
                ('sub_br_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subject')),
            ],
            options={
                'db_table': 'SemAttendance',
                'unique_together': {('stud_id', 'sub_br_id')},
            },
        ),
    ]
